routes/web.php
<?php

use App\Http\Controllers\Auxiliar\AuxiliarController;
use App\Http\Controllers\Auxiliar\ConformidadCargaController;
use App\Http\Controllers\Cias\CiasController;
use App\Http\Controllers\DevController;
use App\Http\Controllers\ExcelExport\AdminExcelController;
use App\Http\Controllers\ExcelExport\UserExcelController;
use App\Http\Controllers\ImportJdeController;
use App\Http\Controllers\Operador\OperadorController;
use App\Http\Controllers\Reportes\ReportesController;
use App\Http\Controllers\Reportes\ReportesProgramacionController;
use App\Http\Controllers\UtilPlacasController;
use Illuminate\Support\Facades\Route;



/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/
/** rutas para desarrollo
 * se borran al final
 */
Route::post('borrando/datos/tablas', [DevController::class, 'borrarDatosTablas'])->name('dev.borrar.datos');

/** fin rutas desarrollo */


Route::get('/', function () {
    return view('inicio');
});

Route::middleware([
    'auth:sanctum',
    config('jetstream.auth_session'),
    'verified'
])->group(function () {
    Route::get('/dashboard', function () {
        return view('dashboard');
    })->name('dashboard');
});
//Route Hooks - Do not delete//
Route::prefix('sdc')->middleware('auth')->group(function(){
    Route::view('pedidos/destino', 'livewire.pedidos-destinos.index')->name('pedidos.destino.index');
	Route::view('destinos', 'livewire.destinos.index')->name('destinos.index');
    Route::view('vehiculo', 'livewire.vehiculos.index')->name('vehivulos.index');
	Route::view('tipo/vehiculo', 'livewire.tipo-vehiculos.index')->name('tipo.vehiculos.index');
	Route::view('companias/transporte', 'livewire.transporte-cias.index')->name('cia.ransporte.index');
	Route::view('transportistas', 'livewire.transportistas.index')->name('transportistas.index');
	Route::view('datos', 'livewire.datos.index')->name('datos.index');
});

/**rutas para usuarios de cias */
Route::prefix('sdc/transportistas')->middleware('auth')->group(function(){
    Route::get('habilitar/placas', [CiasController::class, 'index'] )->name('cias.placas.index');
    Route::get('historial/envios', [CiasController::class, 'historialEnvios'] )->name('cias.historial.envios');
    Route::post('buscar/historial/envios', [CiasController::class, 'historialEnviosBuscar'] )->name('cias.buscar.historial.envios');
    Route::get('habilitar/placas/complementos', [CiasController::class, 'verVomplementos'] )->name('cias.ver.complementos');
    Route::get('ver/placas/lista/habilitadas', [CiasController::class, 'verPlacasHabilitadas'] )->name('cias.ver.placas.habilitadas');
    Route::post('ver/placas/lista/habilitadass', [CiasController::class, 'buscarPlacasHabilitadas'] )->name('cias.buscar.placas.habilitadas');
});
/***rutas para auxilar */
Route::prefix('sdc/auxiliar')->middleware('auth')->group(function(){
    Route::get('habilitar/placas', [AuxiliarController::class, 'index'] )->name('aux.placas.index');
    Route::get('habilitar/placas/compania/{cia}', [AuxiliarController::class, 'verPlacasCompania'] )->name('aux.placas.compania');
    Route::get('colas/vehiculos', [AuxiliarController::class, 'colas'] )->name('aux.colas.index');
    Route::post('colas/eliminar/{cola}', [AuxiliarController::class, 'deletePlacaCola'] )->name('aux.colas.delete.placa');
    Route::post('colas/confirmar/placa/envida', [AuxiliarController::class, 'confirmarPlacaEnviada'] )->name('aux.colas.confirmar.placa');
    Route::post('colas/elimiar/placa/lista/enviados', [AuxiliarController::class, 'eliminarPlacaEnviada'] )->name('aux.colas.eliminar.placa');
});

/***rutas para operador */
Route::prefix('sdc/operador')->middleware('auth')->group(function(){
    Route::get('programacion/placas', [OperadorController::class, 'programacion'] )->name('ope.programacion');
    Route::post('generar/programacion', [OperadorController::class, 'generarProgramacion'] )->name('ope.generar.programacion');
    Route::get('ver/programacion/{fecha}', [OperadorController::class, 'verProgramacion'] )->name('ope.ver.programacion');
    Route::get('ver/complemento/{fecha}', [OperadorController::class, 'verComplemento'] )->name('ope.ver.complemento');
    Route::get('reportes', [OperadorController::class, 'reportes'] )->name('ope.reportes');
    Route::post('complemento/publicar', [OperadorController::class, 'publicarComplemento'] )->name('ope.publicar.complemento');
    Route::get('complemento/publicados', [OperadorController::class, 'verComplementoPublicado'] )->name('ope.ver.complemento.publicado');
});

/**rutas para reportes */
Route::prefix('sdc/reportes')->middleware('auth')->group(function(){
    Route::get('programacion', [ReportesController::class, 'programacion'] )->name('rpt.programacion');
    Route::get('colas/{tipo}', [ReportesController::class, 'colasTipo'] )->name('rpt.colas');
    Route::get('programacion/imprimir/{fecha}', [ReportesController::class, 'imprimirProgramacion'] )->name('rpt.impr.programacion');
    Route::get('programacion/excel/{fecha}', [ReportesController::class, 'programacionExcel'] )->name('rpt.excel.programacion');
    Route::get('programacion/imprimir/sindicatos/{fecha}', [ReportesController::class, 'imprimirProgramacionDetalle'] )->name('rpt.impr.programacion.sindicato');
    Route::get('pedidos/pendientes', [ReportesController::class, 'imprimirPedidosPendientes'] )->name('rpt.impr.pedidos.pendientes');
});

    Route::view('pedidos_destino', 'livewire.pedidos_destino.index')->middleware('auth');
	Route::view('destinos', 'livewire.destinos.index')->middleware('auth');
/**rutas para importar desde excel */
Route::prefix('sdc/import/excel')->middleware('auth')->group(function(){
    Route::get('conocimiento/carga/jde', [ImportJdeController::class, 'importConocimientoJdeShow'] )->name('import.excel.conocimiento.jde.show');
    Route::post('conocimiento/carga/jde', [ImportJdeController::class, 'importConocimientoJdeStore'] )->name('import.excel.conocimiento.jde.store');
});

/** ver reporte de placas */
Route::prefix('sdc/')->middleware('auth')->group(function(){
    Route::get('buscar/viajes/placa', [UtilPlacasController::class, 'buscarViajesPlaca'] )->name('buscar.viajes.placa');
});
/** rutas para reportes */
Route::prefix('sdc/reportes/')->name('rpt.')->middleware('auth')->group(function(){
    Route::get('programacion/sindicatos', [ReportesProgramacionController::class, 'programacionesXSindicatoView'] )->name('programacion.cias.show');
    Route::post('programacion/sindicatos', [ReportesProgramacionController::class, 'programacionesXSindicato'] )->name('programacion.cias');
});

/**rutas para excel */
Route::get('/exportar/excel', [UserExcelController::class, 'exportUsers']);
Route::prefix('excel/exportar')->name('excel.exports.')->middleware('auth')->group(function(){
    Route::get('/colas', [AdminExcelController::class, 'exportColas'])->name('colas');
    Route::get('/Pedidos', [AdminExcelController::class, 'exportPedidos'])->name('pedidos');
    Route::get('/placas/habilitadas/sindicatos/{cia_id}', [AdminExcelController::class, 'exportPlacasHabilitadasSindicato'])->name('sindicado.placa.habilitada');
});

/** rutas para ver conocimientos de carga o conformidad */
Route::prefix('sdc/')->middleware('auth')->group(function(){
    Route::get('ver/conformidad', [ConformidadCargaController::class, 'verConformidad'] )->name('ver.conformidad');
    Route::post('ver/conformidad', [ConformidadCargaController::class, 'buscarConformidad'] )->name('buscar.conformidad');
});

app/Http/Controllers/Auxiliar/AuxiliarController.php
<?php

namespace App\Http\Controllers\Auxiliar;

use App\Http\Controllers\Controller;
use App\Models\CiasHabilitarPlaca;
use App\Models\Cola;
use App\Models\ConocimientoCarga;
use App\Models\TransporteCia;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class AuxiliarController extends Controller
{
    function index() {
        $listaPlacasCias = DB::table('cias_habilitar_placas as chp')
                               ->join('vehiculos as v', 'chp.placa', '=', 'v.Placa' )
                               ->join('transporte_cias as tc', 'v.transporte_cia_id', '=', 'tc.id')
                               ->where('chp.enviado', '1')
                               ->where('chp.programado', '0')
                               ->select('tc.id','tc.nombre', DB::raw('count(*) as cantidad'))
                               ->groupBy('tc.id','tc.nombre')
                               ->get();
        // dd($placaVehiculoCias);
        // $listaPlacasRevisar = CiasHabilitarPlaca::where('enviado', '1')
        //                                         ->where('programado', 0)
        //                                         ->get();
        return view('auxiliar.index')->with(compact('listaPlacasCias'));
    }

    function verPlacasCompania(TransporteCia $cia) {
        $placasCia = DB::table('cias_habilitar_placas as chp')
                        ->select('chp.id as chp_id', 'chp.fecha', 'chp.placa', 'chp.cia_id', 'chp.conocimiento_enviado', 'c.id as cola_id', 'c.tipo_cola', 'c.created_at as cola_fecha', 'c.asignado', 'c.preasignado')
                        ->join('transporte_cias as tc', 'chp.cia_id', '=', 'tc.id')
                        ->join('vehiculos as v', function ($join) {
                            $join->on('tc.id', '=', 'v.transporte_cia_id')
                                ->on('chp.placa', '=', 'v.placa');
                        })
                        ->leftJoin('colas as c', 'v.id', '=', 'c.vehiculo_id')
                        ->where('chp.enviado', '1')
                        ->where('chp.programado', '0')
                        ->where('tc.id', $cia->id)
                        ->get();
        // dd($placasCia);
    return view('auxiliar.ver_placas_habilitar')->with(compact('placasCia', 'cia'));
    }



    function colas() {
        $colaUVS = $this->buscarCola('UVS');
        $colaUVI = $this->buscarCola('UVI');
        $colaUVP = $this->buscarCola('UVP');
        return view('auxiliar.colas')->with(compact('colaUVS','colaUVI','colaUVP'));
    }

    protected function buscarCola($tipoCola) {
        return Cola::select('colas.id', 'colas.tipo_cola', 'colas.fecha', 'colas.asignado', 'colas.preasignado', 'colas.conocimiento_carga_id', 'transporte_cias.nombre', 'vehiculos.placa', 'vehiculos.capacidad_arrastre as capacidad')
        ->join('vehiculos', 'colas.vehiculo_id', '=', 'vehiculos.id')
        ->join('transporte_cias', 'vehiculos.transporte_cia_id', '=', 'transporte_cias.id')
        ->where('colas.tipo_cola', $tipoCola)
        ->where('colas.asignado', '0')
        ->where('colas.preasignado', '0')
        ->orderBy('colas.fecha', 'asc')
        ->get();
    }

    public function deletePlacaCola(Cola $cola) {
        /**
         * 1.- cias_habilitar_placas->programado = 1;
         * 2.- eliminar conocimiento de carga
         * 3.- eliminar cola
         */
        DB::beginTransaction();
        try {
            $conocimientoCarga = ConocimientoCarga::find($cola->conocimiento_carga_id);
            $placaEliminar = $conocimientoCarga->placa;
            $cias_habilitar_placas = CiasHabilitarPlaca::find($conocimientoCarga->cias_habilitar_placas_id);
            $cias_habilitar_placas->programado = 0;
            $cias_habilitar_placas->save();
            $cola->delete();
            $conocimientoCarga->delete();
            DB::commit();
            session()->flash('message', 'Se elimino la placa: '.$placaEliminar );
            // $this->emit('closeModal');
        } catch (\Exception $e) {
            // En caso de error, deshacemos la transacción $e->getMessage()
            DB::rollback();
            session()->flash('message', 'Ocurrió un error! No se puede eliminar la placa '.$placaEliminar . ' de la cola ' . $e->getMessage() );

        }
        return redirect()->route('aux.colas.index');
    }

    public function confirmarPlacaEnviada(Request $request){
        // dd($request->all());
        $chp = CiasHabilitarPlaca::findOrFail($request->chp_id);
        if($chp->placa === $request->placa){
            $chp->programado = 1;
            $chp->save();
            session()->flash('message', 'Se volvio a confirmar la placa: '.$chp->placa  );
        }
        return redirect()->route('aux.placas.compania', [$chp->cia_id]);
    }

    public function eliminarPlacaEnviada(Request $request) {
        $ciasHabiPlaca = CiasHabilitarPlaca::findorFail($request->chp_id);
        $ciasHabiPlaca->delete();
        session()->flash('message', 'Se eliminó la placa: '.$ciasHabiPlaca->placa  );
        return redirect()->route('aux.placas.compania', [$ciasHabiPlaca->cia_id]);
    }


}

app/Http/Controllers/Auxiliar/ConformidadCargaController.php
<?php

namespace App\Http\Controllers\Auxiliar;

use App\Http\Controllers\Controller;
use App\Models\ConocimientoCargaJde;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class ConformidadCargaController extends Controller
{
    function verConformidad() {
        return view('auxiliar.ver_conformidad');
    }

    function buscarConformidad(Request $request) {
        // dd($request->all());
        $fuente =  $request->fuente;
        $buscar_por =  $request->buscar_por;
        $buscado = $request->search;
        if($fuente == "sdc"){
            $datos = $this->buscarConocimientosSDC($buscar_por, $buscado);
        }else { //jde
            $datos = $this->buscarConocimientosJDE($buscar_por, $buscado);
        }
        return view('auxiliar.ver_conformidad')->with(compact('datos'));
    }

    private function buscarConocimientosJDE($buscar_por, $buscado) {
        $query = ConocimientoCargaJde::query();
        if($buscar_por == "placa"){
            $query->where('placa', $buscado);
        }else //conformidad
        {
            $query->where('numero_carga', $buscado);
        }
        $query->orderBy('fecha', 'desc');
        return $query->get();
    }

    private function buscarConocimientosSDC($buscar_por, $buscado) {
        $query = DB::table('conocimiento_cargas as cc')
                    ->join('destinos as d','cc.ultimo_destino_id', '=', 'd.id' )
                    ->select('cc.numero_carga', 'd.nombre_destino as ciudad', 'cc.fecha_carguio as fecha', 'cc.placa');
        // dd($query->get());
        if($buscar_por == "placa"){
            $query->where('placa', $buscado);
        }else //conformidad
        {
            $query->where('numero_carga', $buscado);
        }
        return $query->where('habilitado', '1')
                     ->orderBy('fecha_carguio', 'desc')
                     ->get();
    }
}

app/Http/Livewire/Auxiliar/HabilitarPlaca.php
<?php

namespace App\Http\Livewire\Auxiliar;

use App\Models\CiasHabilitarPlaca;
use App\Models\TransporteCia;
use Illuminate\Support\Facades\DB;
use Livewire\Component;

class HabilitarPlaca extends Component
{
    public $cia_id, $placa;
    public $cia;

    public function rules()
    {
        return [
            'placa' => 'required',
        ];
    }

    public function messages()
    {
        return [
            'placa' => 'Debe ingresar un placa',
        ];
    }

    public function mount() {
        $this->cia = TransporteCia::find($this->cia_id);
    }

    public function render()
    {
        return view('livewire.auxiliar.habilitar-placa');
    }

    function cancel() {
        $this->emit('closeModalEdit');
    }

    function ingresarNuevaPlaca() {
        $this->validate();
        $placaCia = DB::table('transporte_cias as tc')
                    ->join('vehiculos as v', 'tc.id', '=', 'v.transporte_cia_id')
                    ->select('tc.id as tc_id','v.id as vehiculo_id', 'v.placa')
                    ->where('v.activo', '1')
                    ->where('tc.id', $this->cia->id)
                    ->where('v.placa', $this->placa)
                    ->first();
        // dd($placaCia);
        if(is_null($placaCia)){
            session()->flash('message', 'La placa no pertenece al este sindicato');
        } else {
            $placaEnLista = DB::table('cias_habilitar_placas as chp')
                        ->select('chp.id as chp_id', 'chp.fecha', 'chp.placa', 'chp.cia_id', 'chp.conocimiento_enviado', 'c.id as cola_id', 'c.tipo_cola', 'c.created_at as cola_fecha', 'c.asignado', 'c.preasignado')
                        ->join('transporte_cias as tc', 'chp.cia_id', '=', 'tc.id')
                        ->join('vehiculos as v', function ($join) {
                            $join->on('tc.id', '=', 'v.transporte_cia_id')
                                ->on('chp.placa', '=', 'v.placa');
                        })
                        ->leftJoin('colas as c', 'v.id', '=', 'c.vehiculo_id')
                        ->where('chp.enviado', '1')
                        ->where('chp.programado', '0')
                        ->where('tc.id', $this->cia->id)
                        ->where('v.placa', $this->placa)
                        ->first();
            if(is_null($placaEnLista)){
                $prueba = CiasHabilitarPlaca::create(['placa' => $this->placa,'cia_id'=>$this->cia_id,
                                                    'enviado' => '1', 'conocimiento_enviado' => '1']);
                // dd($prueba);
                session()->flash('message', 'Se añadio una nueva placa para su revisión');
                return redirect()->route('aux.placas.compania',[$this->cia->id]);
            }else{
                session()->flash('message', 'La placa ya se encuentra en la lista de este sindicato');
            }
        }
    }
}

resources/views/auxiliar/colas.blade.php
@extends('adminlte::page')

@section('title', 'Ver Colas')

@section('content_header')
<h1>Colas de vehículos</h1>
<div class="row">
    <div class="x">
        <a class="btn btn-sm btn-success" target="_blank" href="{{route('rpt.colas',['UVS'])}}"><i class="far fa-file-pdf"></i>&nbsp; COLA UVS</a>
        <a class="btn btn-sm btn-success" target="_blank" href="{{route('rpt.colas',['UVI'])}}"><i class="far fa-file-pdf"></i>&nbsp; COLA UVI</a>
        <a class="btn btn-sm btn-success" target="_blank" href="{{route('rpt.colas',['UVP'])}}"><i class="far fa-file-pdf"></i>&nbsp; COLA UVP</a>
        <a class="btn btn-sm btn-info" href="{{route('excel.exports.colas')}}"> <i class="far fa-file-excel"></i> Colas</a>
    </div>
</div>
@stop

@section('content')

<div class="container-fluid">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="row">
                @if (session()->has('message'))
                    <div wire:poll.4s class="btn btn-sm btn-success" style="margin-top:0px; margin-bottom:0px;"> {{ session('message') }} </div>
                @endif
            </div>
            <div class="row">
                <div class="col-md-6">
                    <h4>COLA UVS</h4>
                </div>
                <div class="col-md-6">
                    <a class="btn btn-sm btn-info float-right" target="_blank" href="{{route('rpt.colas',['UVS'])}}">Imprimir</a>
                </div>
            </div>
            <table class="table table-bordered table-sm table-striped">
                <thead>
                    <tr>
                        <th>#</th>
                        <th>Fecha</th>
                        <th>Placa</th>
                        <th>Capacidad</th>
                        <th>Sindicato</th>
                        <th width="10px" >Acción</th>
                    </tr>
                </thead>
                <tbody>
                    @php
                        $i=0;
                    @endphp
                    @foreach ($colaUVS as $item)
                        <tr>
                            <td>{{++$i}}</td>
                            @php
                                // dd($item->fecha);
                                $fecha = DateTime::createFromFormat('Y-m-d H:i:s.u', $item->fecha);
                            @endphp
                            <td>{{$fecha->format('d/m/Y')}}</td>
                            <td>{{$item->placa}}</td>
                            <td>{{$item->capacidad}}</td>
                            <td>{{$item->nombre}}
                            </td>
                            <td>
                                <form action="{{route('aux.colas.delete.placa',[$item->id])}}" method="post">
                                    @csrf
                                    <button class="btn btn-primary btn-sm">Eliminar</button>
                                </form>
                            </td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
        <div class="col-md-12">
            <div class="row">
                <div class="col-md-6">
                    <h4>COLA UVI</h4>
                </div>
                <div class="col-md-6">
                    <a class="btn btn-sm btn-info float-right" target="_blank" href="{{route('rpt.colas',['UVI'])}}">Imprimir</a>
                </div>
            </div>
            <table class="table table-bordered table-sm table-striped">
                <thead>
                    <tr>
                        <th>#</th>
                        <th>Fecha</th>
                        <th>Placa</th>
                        <th>Capacidad</th>
                        <th>Sindicato</th>
                        <th width="10px" >Acción</th>

                    </tr>
                </thead>
                <tbody>
                    @php
                        $i=0;
                    @endphp
                    @foreach ($colaUVI as $item)
                        <tr>
                            <td>{{++$i}}</td>
                            @php
                                $fecha = DateTime::createFromFormat('Y-m-d H:i:s.u', $item->fecha);
                            @endphp
                            <td>{{$fecha->format('d/m/Y')}}</td>
                            <td>{{$item->placa}}</td>
                            <td>{{$item->capacidad}}</td>
                            <td>{{$item->nombre}}</td>
                            <td>
                                <form action="{{route('aux.colas.delete.placa',[$item->id])}}" method="post">
                                    @csrf
                                    <button class="btn btn-primary btn-sm">Eliminar</button>
                                </form>
                            </td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
        <div class="col-md-12">
            <div class="row">
                <div class="col-md-6">
                    <h4>COLA UVP</h4>
                </div>
                <div class="col-md-6">
                    <a class="btn btn-sm btn-info float-right" target="_blank" href="{{route('rpt.colas',['UVP'])}}">Imprimir</a>
                </div>
            </div>
            <table class="table table-bordered table-sm table-striped">
                <thead>
                    <tr>
                        <th>#</th>
                        <th>Fecha</th>
                        <th>placa</th>
                        <th>Capacidad</th>
                        <th>Sindicato</th>
                        <th width="10px" >Acción</th>

                    </tr>
                </thead>
                <tbody>
                    @php
                        $i=0;
                    @endphp
                    @foreach ($colaUVP as $item)
                        <tr>
                            <td>{{++$i}}</td>
                            @php
                                $fecha = DateTime::createFromFormat('Y-m-d H:i:s.u', $item->fecha);
                            @endphp
                            <td>{{$fecha->format('d/m/Y')}}</td>
                            <td>{{$item->placa}}</td>
                            <td>{{$item->capacidad}}</td>
                            <td>{{$item->nombre}}</td>
                            <td>
                                <form action="{{route('aux.colas.delete.placa',[$item->id])}}" method="post">
                                    @csrf
                                    <button class="btn btn-primary btn-sm">Eliminar</button>
                                </form>
                            </td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
        <div class="col-md-12">

        </div>
    </div>
</div>
@stop


@section('css')
    <link rel="stylesheet" href="/css/admin_custom.css">
@stop

@section('js')

@stop

resources/views/auxiliar/index.blade.php
@extends('adminlte::page')

@section('title', 'Habilitar Placas')

@section('content_header')
<h1>Habilitar Vehículos Compañias</h1>
@stop

@section('content')
<div class="container-fluid">
    <div class="row justify-content-center">
        <div class="col-md-12">
            {{-- @livewire('utiles.crear-conocimiento-carga', ['id' => 1]) --}}
            <table class="table table-bordered table-sm table-striped">
                <thead>
                    <tr>
                        <th>#</th>
                        <th>Compañia de transporte</th>
                        <th>Cantidad</th>
                        <th>Acción</th>
                    </tr>
                </thead>
                <tbody>
                    @php
                        $i=0;
                    @endphp
                    @foreach ($listaPlacasCias as $item)
                        <tr>
                            <td>{{++$i}}</td>
                            <td>{{$item->nombre}}</td>
                            <td>{{$item->cantidad}}</td>
                            <td>
                                <a href="{{route('aux.placas.compania',[$item->id])}}" class="btn btn-sm btn-success">Ver Placas</a>
                            </td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
</div>
@stop


@section('css')
    <link rel="stylesheet" href="/css/admin_custom.css">
@stop

@section('js')

@stop

resources/views/auxiliar/ver_conformidad.blade.php
@extends('adminlte::page')

@section('title', 'Reportes de Conformidad de Carga')

@section('content_header')
<h1>Ver Conformidad de Carga</h1>
@stop

@section('content')
<div class="container-fluid">
    <form action="{{route('buscar.conformidad')}}" method="post">
        @csrf
        <div class="row justify-content-center">
                <fieldset class="col-md-4">
                    <legend>Fuente de datos</legend>
                    <div class="form-group">
                      <label for="">
                          <input type="radio" name="fuente" value="sdc" id="tabla1" checked>
                          SDC
                      </label>
                      <label for="">
                          <input type="radio" name="fuente" value="jde" id="tabla2">
                            JDE
                      </label>
                    </div>
                </fieldset>
                <fieldset class="col-md-4">
                    <legend>Buscar por</legend>
                    <div class="form-group">
                        <label for="">
                          <input type="radio" name="buscar_por" value="conformidad" id="buspor_1" checked> Conformidad
                        </label>
                        <label for="">
                          <input type="radio" name="buscar_por" value="placa" id="buspor_2" > Placa
                        </label>
                    </div>
                </fieldset>
                <fieldset class="col-md-4">
                    <legend>&nbsp;</legend>
                    <div class="row">
                        <div class="col-6">
                            <div class="form-group">
                                  <input class="form-control" type="text" name="search" placeholder="Conocimiento / Placa" required >
                            </div>
                        </div>
                        <div class="col-6">
                            <input class="btn btn-primary" type="submit" value="Buscar">
                        </div>
                    </div>

                </fieldset>
        </div>
    </form>
    @isset($datos)
    <div>
        <div class="card border-primary">
          <img class="card-img-top" src="holder.js/100px180/" alt="">
          <div class="card-body">
            <table class="table table-sm table-striped">
                <thead>
                    <tr>
                        <th>Número de carga</th>
                        <th>Fecha Registro</th>
                        <th>Placa</th>
                        <th>Destino</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach ($datos as $item)
                        <tr>
                            <td>{{$item->numero_carga}}</td>
                            <td>{{$item->fecha}}</td>
                            <td>{{$item->placa}}</td>
                            <td>{{$item->ciudad}}</td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
          </div>
        </div>
    </div>
    @endisset

</div>
@stop


@section('css')
    <link rel="stylesheet" href="/css/admin_custom.css">
@stop

@section('js')

@stop