routes/web.php
<?php

use App\Http\Controllers\Auxiliar\AuxiliarController;
use App\Http\Controllers\Auxiliar\ConformidadCargaController;
use App\Http\Controllers\Cias\CiasController;
use App\Http\Controllers\DevController;
use App\Http\Controllers\ExcelExport\AdminExcelController;
use App\Http\Controllers\ExcelExport\UserExcelController;
use App\Http\Controllers\ImportJdeController;
use App\Http\Controllers\Operador\OperadorController;
use App\Http\Controllers\Reportes\ReportesController;
use App\Http\Controllers\Reportes\ReportesProgramacionController;
use App\Http\Controllers\UtilPlacasController;
use Illuminate\Support\Facades\Route;



/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/
/** rutas para desarrollo
 * se borran al final
 */
Route::post('borrando/datos/tablas', [DevController::class, 'borrarDatosTablas'])->name('dev.borrar.datos');

/** fin rutas desarrollo */


Route::get('/', function () {
    return view('inicio');
});

Route::middleware([
    'auth:sanctum',
    config('jetstream.auth_session'),
    'verified'
])->group(function () {
    Route::get('/dashboard', function () {
        return view('dashboard');
    })->name('dashboard');
});
//Route Hooks - Do not delete//
Route::prefix('sdc')->middleware('auth')->group(function(){
    Route::view('pedidos/destino', 'livewire.pedidos-destinos.index')->name('pedidos.destino.index');
	Route::view('destinos', 'livewire.destinos.index')->name('destinos.index');
    Route::view('vehiculo', 'livewire.vehiculos.index')->name('vehivulos.index');
	Route::view('tipo/vehiculo', 'livewire.tipo-vehiculos.index')->name('tipo.vehiculos.index');
	Route::view('companias/transporte', 'livewire.transporte-cias.index')->name('cia.ransporte.index');
	Route::view('transportistas', 'livewire.transportistas.index')->name('transportistas.index');
	Route::view('datos', 'livewire.datos.index')->name('datos.index');
});

/**rutas para usuarios de cias */
Route::prefix('sdc/transportistas')->middleware('auth')->group(function(){
    Route::get('habilitar/placas', [CiasController::class, 'index'] )->name('cias.placas.index');
    Route::get('historial/envios', [CiasController::class, 'historialEnvios'] )->name('cias.historial.envios');
    Route::post('buscar/historial/envios', [CiasController::class, 'historialEnviosBuscar'] )->name('cias.buscar.historial.envios');
    Route::get('habilitar/placas/complementos', [CiasController::class, 'verVomplementos'] )->name('cias.ver.complementos');
    Route::get('ver/placas/lista/habilitadas', [CiasController::class, 'verPlacasHabilitadas'] )->name('cias.ver.placas.habilitadas');
    Route::post('ver/placas/lista/habilitadass', [CiasController::class, 'buscarPlacasHabilitadas'] )->name('cias.buscar.placas.habilitadas');
});
/***rutas para auxilar */
Route::prefix('sdc/auxiliar')->middleware('auth')->group(function(){
    Route::get('habilitar/placas', [AuxiliarController::class, 'index'] )->name('aux.placas.index');
    Route::get('habilitar/placas/compania/{cia}', [AuxiliarController::class, 'verPlacasCompania'] )->name('aux.placas.compania');
    Route::get('colas/vehiculos', [AuxiliarController::class, 'colas'] )->name('aux.colas.index');
    Route::post('colas/eliminar/{cola}', [AuxiliarController::class, 'deletePlacaCola'] )->name('aux.colas.delete.placa');
    Route::post('colas/confirmar/placa/envida', [AuxiliarController::class, 'confirmarPlacaEnviada'] )->name('aux.colas.confirmar.placa');
    Route::post('colas/elimiar/placa/lista/enviados', [AuxiliarController::class, 'eliminarPlacaEnviada'] )->name('aux.colas.eliminar.placa');
});

/***rutas para operador */
Route::prefix('sdc/operador')->middleware('auth')->group(function(){
    Route::get('programacion/placas', [OperadorController::class, 'programacion'] )->name('ope.programacion');
    Route::post('generar/programacion', [OperadorController::class, 'generarProgramacion'] )->name('ope.generar.programacion');
    Route::get('ver/programacion/{fecha}', [OperadorController::class, 'verProgramacion'] )->name('ope.ver.programacion');
    Route::get('ver/complemento/{fecha}', [OperadorController::class, 'verComplemento'] )->name('ope.ver.complemento');
    Route::get('reportes', [OperadorController::class, 'reportes'] )->name('ope.reportes');
    Route::post('complemento/publicar', [OperadorController::class, 'publicarComplemento'] )->name('ope.publicar.complemento');
    Route::get('complemento/publicados', [OperadorController::class, 'verComplementoPublicado'] )->name('ope.ver.complemento.publicado');
});

/**rutas para reportes */
Route::prefix('sdc/reportes')->middleware('auth')->group(function(){
    Route::get('programacion', [ReportesController::class, 'programacion'] )->name('rpt.programacion');
    Route::get('colas/{tipo}', [ReportesController::class, 'colasTipo'] )->name('rpt.colas');
    Route::get('programacion/imprimir/{fecha}', [ReportesController::class, 'imprimirProgramacion'] )->name('rpt.impr.programacion');
    Route::get('programacion/excel/{fecha}', [ReportesController::class, 'programacionExcel'] )->name('rpt.excel.programacion');
    Route::get('programacion/imprimir/sindicatos/{fecha}', [ReportesController::class, 'imprimirProgramacionDetalle'] )->name('rpt.impr.programacion.sindicato');
    Route::get('pedidos/pendientes', [ReportesController::class, 'imprimirPedidosPendientes'] )->name('rpt.impr.pedidos.pendientes');
});

    Route::view('pedidos_destino', 'livewire.pedidos_destino.index')->middleware('auth');
	Route::view('destinos', 'livewire.destinos.index')->middleware('auth');
/**rutas para importar desde excel */
Route::prefix('sdc/import/excel')->middleware('auth')->group(function(){
    Route::get('conocimiento/carga/jde', [ImportJdeController::class, 'importConocimientoJdeShow'] )->name('import.excel.conocimiento.jde.show');
    Route::post('conocimiento/carga/jde', [ImportJdeController::class, 'importConocimientoJdeStore'] )->name('import.excel.conocimiento.jde.store');
});

/** ver reporte de placas */
Route::prefix('sdc/')->middleware('auth')->group(function(){
    Route::get('buscar/viajes/placa', [UtilPlacasController::class, 'buscarViajesPlaca'] )->name('buscar.viajes.placa');
});
/** rutas para reportes */
Route::prefix('sdc/reportes/')->name('rpt.')->middleware('auth')->group(function(){
    Route::get('programacion/sindicatos', [ReportesProgramacionController::class, 'programacionesXSindicatoView'] )->name('programacion.cias.show');
    Route::post('programacion/sindicatos', [ReportesProgramacionController::class, 'programacionesXSindicato'] )->name('programacion.cias');
});

/**rutas para excel */
Route::get('/exportar/excel', [UserExcelController::class, 'exportUsers']);
Route::prefix('excel/exportar')->name('excel.exports.')->middleware('auth')->group(function(){
    Route::get('/colas', [AdminExcelController::class, 'exportColas'])->name('colas');
    Route::get('/Pedidos', [AdminExcelController::class, 'exportPedidos'])->name('pedidos');
    Route::get('/placas/habilitadas/sindicatos/{cia_id}', [AdminExcelController::class, 'exportPlacasHabilitadasSindicato'])->name('sindicado.placa.habilitada');
});

/** rutas para ver conocimientos de carga o conformidad */
Route::prefix('sdc/')->middleware('auth')->group(function(){
    Route::get('ver/conformidad', [ConformidadCargaController::class, 'verConformidad'] )->name('ver.conformidad');
    Route::post('ver/conformidad', [ConformidadCargaController::class, 'buscarConformidad'] )->name('buscar.conformidad');
});

app/Http/Controllers/Cias/CiasController.php
<?php

namespace App\Http\Controllers\Cias;

use App\Http\Controllers\Controller;

use Carbon\Carbon;
use Illuminate\Support\Facades\Session;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;

class CiasController extends Controller
{
    function index() {
        // $cia = Auth::user()->transporteCias->first();
        return view('cias.index');
    }
    function historialEnvios() {
        return view('cias.historial_envios');
    }

    function historialEnviosBuscar(Request $request){
        // dd($request->all());
        $fechaIni = $request->get('fecha_ini');// Carbon::createFromFormat('Y-m-d', $request->get('fecha_ini'));
        $fechaFin = $request->get('fecha_fin');
        if(is_null($fechaFin)){
            $fechaFin = $fechaIni;
        }else{
            $fechaFin = Carbon::createFromFormat('Y-m-d', $fechaFin);
        }
        $listaPlacas = DB::table('cias_habilitar_placas as chp')
                        // ->select('*')
                        ->selectRaw('chp.id, chp.placa, chp.enviado, chp.programado, chp.cia_id, date(chp.fecha) AS fecha')
                        ->where('chp.enviado', 1)
                        ->where('chp.cia_id', session()->get('cia_id'))
                        ->whereBetween('chp.fecha', [$fechaIni, $fechaFin])
                        ->get();
        // dd($listaPlacas);
        return view('cias.historial_envios')->with(compact('listaPlacas'));
    }

    function verVomplementos() {

        return view('cias.ver_complementos');//->with(compact('listaComplementos','tipoVehiculos'))
    }
    public function verPlacasHabilitadas(){
        return view('cias.placas_habilitadas_auxiliar');
    }
    public function buscarPlacasHabilitadas(Request $request) {
        $placasHabilitadas =  DB::table('colas as c')
                                ->select('c.id as cola_id', 'c.tipo_cola', DB::raw("DATE_FORMAT(c.created_at, '%d-%m-%Y') as fecha_habilitado"),
                                    'v.id as vehiculo_id', 'v.placa', 'tv.tipo', 'cc.numero_carga',
                                    DB::raw("DATE_FORMAT(cc.fecha_carguio, '%d-%m-%Y') as fecha_carguio"),
                                    'd.nombre_destino as ultimo_destino', 'tc.id as cia_id', 'tc.nombre')
                                ->join('vehiculos as v', 'c.vehiculo_id', '=', 'v.id')
                                ->join('tipo_vehiculos as tv', 'v.tipo_vehiculo_id', '=', 'tv.id')
                                ->join('conocimiento_cargas as cc', 'c.conocimiento_carga_id', '=', 'cc.id')
                                ->join('destinos as d', 'cc.ultimo_destino_id', '=', 'd.id')
                                ->join('transporte_cias as tc', 'v.transporte_cia_id', '=', 'tc.id')
                                ->whereDate('c.created_at', '=', '2023-10-23')
                                ->where('tc.id', '=', Session::get('cia_id'))
                                ->get();
        // dd($placasHabilitadas);
        return view('cias.placas_habilitadas_auxiliar')->with(compact('placasHabilitadas'));
    }
}

app/Http/Livewire/Auxiliar/HabilitarPlaca.php
<?php

namespace App\Http\Livewire\Auxiliar;

use App\Models\CiasHabilitarPlaca;
use App\Models\TransporteCia;
use Illuminate\Support\Facades\DB;
use Livewire\Component;

class HabilitarPlaca extends Component
{
    public $cia_id, $placa;
    public $cia;

    public function rules()
    {
        return [
            'placa' => 'required',
        ];
    }

    public function messages()
    {
        return [
            'placa' => 'Debe ingresar un placa',
        ];
    }

    public function mount() {
        $this->cia = TransporteCia::find($this->cia_id);
    }

    public function render()
    {
        return view('livewire.auxiliar.habilitar-placa');
    }

    function cancel() {
        $this->emit('closeModalEdit');
    }

    function ingresarNuevaPlaca() {
        $this->validate();
        $placaCia = DB::table('transporte_cias as tc')
                    ->join('vehiculos as v', 'tc.id', '=', 'v.transporte_cia_id')
                    ->select('tc.id as tc_id','v.id as vehiculo_id', 'v.placa')
                    ->where('v.activo', '1')
                    ->where('tc.id', $this->cia->id)
                    ->where('v.placa', $this->placa)
                    ->first();
        // dd($placaCia);
        if(is_null($placaCia)){
            session()->flash('message', 'La placa no pertenece al este sindicato');
        } else {
            $placaEnLista = DB::table('cias_habilitar_placas as chp')
                        ->select('chp.id as chp_id', 'chp.fecha', 'chp.placa', 'chp.cia_id', 'chp.conocimiento_enviado', 'c.id as cola_id', 'c.tipo_cola', 'c.created_at as cola_fecha', 'c.asignado', 'c.preasignado')
                        ->join('transporte_cias as tc', 'chp.cia_id', '=', 'tc.id')
                        ->join('vehiculos as v', function ($join) {
                            $join->on('tc.id', '=', 'v.transporte_cia_id')
                                ->on('chp.placa', '=', 'v.placa');
                        })
                        ->leftJoin('colas as c', 'v.id', '=', 'c.vehiculo_id')
                        ->where('chp.enviado', '1')
                        ->where('chp.programado', '0')
                        ->where('tc.id', $this->cia->id)
                        ->where('v.placa', $this->placa)
                        ->first();
            if(is_null($placaEnLista)){
                $prueba = CiasHabilitarPlaca::create(['placa' => $this->placa,'cia_id'=>$this->cia_id,
                                                    'enviado' => '1', 'conocimiento_enviado' => '1']);
                // dd($prueba);
                session()->flash('message', 'Se añadio una nueva placa para su revisión');
                return redirect()->route('aux.placas.compania',[$this->cia->id]);
            }else{
                session()->flash('message', 'La placa ya se encuentra en la lista de este sindicato');
            }
        }
    }
}

app/Http/Livewire/Cias/ComplementoVehiculosRequeridos.php
<?php

namespace App\Http\Livewire\Cias;

use App\Models\TipoVehiculo;
use Illuminate\Support\Facades\DB;
use Livewire\Component;

class ComplementoVehiculosRequeridos extends Component
{
    public $tipoVehiculos = [];

    protected $listeners = ['refrescarListaComplementos'=> '$refresh'];

    function mount(){
        $this->tipoVehiculos = TipoVehiculo::get()->pluck('tipo','id')->toArray();
    }
    public function render()
    {
        $listaComplementos = DB::table('pedidos_vehiculos_carga as pvc')
        ->leftJoin('programaciones as p', 'pvc.id', '=', 'p.pedidos_vehiculo_carga_id')
        ->where('pvc.complemento', 1)
        // ->where('pvc.publicar', 0)
        ->whereNull('p.pedidos_vehiculo_carga_id')
        ->selectRaw('pvc.tipo_vehiculo_id, count(pvc.tipo_vehiculo_id) as cantidad')
        ->groupByRaw('pvc.tipo_vehiculo_id')
        ->get();


        return view('livewire.cias.complemento-vehiculos-requeridos',['listaComplementos'=>$listaComplementos]);
    }

    // public function refrescarListaComplementos() {
    //     $this->refresh();
    // }
}

app/Http/Livewire/Cias/UpdateConocimientoEnviado.php
<?php

namespace App\Http\Livewire\Cias;

use App\Models\CiasHabilitarPlaca;
use Livewire\Component;

class UpdateConocimientoEnviado extends Component
{
    public $cia_habilitar_placa_id, $isChecked;
    public $cia_habilitar_placa;

    function mount(){
        $this->cia_habilitar_placa = CiasHabilitarPlaca::findOrFail($this->cia_habilitar_placa_id);
        $this->isChecked = $this->cia_habilitar_placa->conocimiento_enviado;
    }

    public function render()
    {
        // dd($this->cia_habilitar_placa_id);
        return view('livewire.cias.update-conocimiento-enviado');
    }

    public function actualizarConocimientoEnviado() {
        $this->cia_habilitar_placa->conocimiento_enviado = $this->isChecked?1:0;
        // dd($this->cia_habilitar_placa);
        $this->cia_habilitar_placa->save();
        // session()->flash('message', 'Se actualizo el campo conocimiento enviado de la placa .'. $this->cia_habilitar_placa->placa);
    }
}

app/Http/Livewire/UtilPlaca/BuscarViajesPlaca.php
<?php

namespace App\Http\Livewire\UtilPlaca;

use App\Models\ConocimientoCargaJde;
use Illuminate\Pagination\LengthAwarePaginator;
use Livewire\Component;
use Livewire\WithPagination;

class BuscarViajesPlaca extends Component
{
    use WithPagination;
	protected $paginationTheme = 'bootstrap';

    public $destinos, $verResultado, $buscarPlaca;

    public function mount() {
        $this->verResultado = false;
    }

    public function render()
    {
        return view('livewire.util-placa.buscar-viajes-placa');
    }

    public function buscarDestinosPlaca(){
        $this->destinos = ConocimientoCargaJde::where('placa', $this->buscarPlaca)->orderBy('fecha', 'desc')->get();
        // dd($this->destinos);
        $this->verResultado=false;
        if($this->destinos->count()) {
            $this->verResultado=true;
        }
        $this->buscarPlaca = "";
        $this->render();
    }
}

resources/views/livewire/cias/complemento-vehiculos-requeridos.blade.php
<div class="col-md-6">
    <div class="card">
        <div class="card-header">
            <h5>Cantidad de vehiculos requeridos para los complementos</h5>
        </div>
        <div class="card-body">
            @if (count($listaComplementos) > 0)
            <table class="table table-sm table-hover">
                <thead>
                    <tr>
                        <th>#</th>
                        <th>TipoVehiculo</th>
                        <th>Cantidad</th>
                    </tr>
                </thead>
                @foreach ($listaComplementos as $item)
                    <tr>
                        <td>{{$loop->iteration}}</td>
                        <td>{{$tipoVehiculos[$item->tipo_vehiculo_id]}}</td>
                        <td>{{$item->cantidad}}</td>
                    </tr>
                @endforeach
            </table>
            @else
                <p>No hay datos</p>
            @endif
        </div>
    </div>
</div>

resources/views/livewire/cias/enviar-placa-complemento.blade.php
<div class="col-md-6">
    {{-- Do your work, then step back. --}}
    <div class="card text-left">
        <div class="card-header">
            <h5>Buscar placa y enviar para asignación inmediata</h5>
        </div>
      <div class="card-body">
        <form class="form-horizontal" wire:submit.prevent="enviarPlacaComplemento">
            <div class="form-group row">
                <div class="col-md-6">
                    <input wire:model='keyPlaca' type="text" class="form-control form-control-sm dropdown {{$verDropdownList}}" name="searchPlaca" id="searchPlaca" placeholder="Buscar placa">
                    @if (!empty($listaPlacas))
                        <div class="dropdown-menu {{$verDropdownList}}" style="top:36px; left:7px" aria-labelledby="dropdownMenuButton">
                            @if ($listaPlacas->count() > 0)
                                @foreach ($listaPlacas as $resultado)

                                    <a class="dropdown-item" href="#" wire:click="seleccionarResultado({{ $resultado->id }})">
                                            {{ $resultado->placa }}
                                    </a>
                                @endforeach
                            @else
                                <span class="mx-2">Sin resultados!!!</span>
                            @endif

                        </div>
                    @endif
                </div>
            </div>
            <div class="form-group row">
                <div class="col-md-6">
                    <span class="form-control form-control-sm">{{$placaTipo}}</span>
                </div>
                <div class="col-md-2">
                    <button class="btn btn-sm btn-primary">enviar</button>
                </div>
            </div>
        </form>
        @if (session()->has('message'))
                <div wire:poll.6s class="btn btn-sm btn-success" style="margin-top:0px; margin-bottom:0px;"> {{ session('message') }} </div>
        @endif
      </div>
    </div>
</div>

resources/views/livewire/cias/habilitar-placas.blade.php
<div class="card">
    <div class="card-header">
        <div style="display: flex; justify-content: space-between;">
            <div class="float-left">
                <h4>Lista placas para enviar </h4>
            </div>
            @if (session()->has('message'))
                <div wire:poll.6s class="btn btn-sm btn-success" style="margin-top:0px; margin-bottom:0px;"> {{ session('message') }} </div>
            @endif
            <div class="col-md-2">
                <input wire:model='keyPlaca' type="text" class="form-control dropdown {{$verDropdownList}}" name="searchPlaca"
                                                id="searchPlaca" placeholder="Placa">
                @if (!empty($listaPlacas))
                    <div class="dropdown-menu {{$verDropdownList}}" style="top:36px; left:7px" aria-labelledby="dropdownMenuButton">
                        @if ($listaPlacas->count() > 0)
                            @foreach ($listaPlacas as $resultado)

                                <a class="dropdown-item" href="#" wire:click="seleccionarResultado({{ $resultado->id }})">
                                        {{ $resultado->placa }}
                                </a>
                            @endforeach
                        @else
                            <span class="mx-2">Sin resultados!!!</span>
                        @endif

                    </div>
                @endif
            </div>
            {{-- @if (session()->has('message'))
                <div wire:poll.4s class="btn btn-sm btn-success" style="margin-top:0px; margin-bottom:0px;"> {{ session('message') }} </div>
            @endif --}}
            {{-- <div class="btn btn-sm btn-info" data-bs-toggle="modal" data-bs-target="#createDataModal">
            <i class="fa fa-plus"></i>  Buscar
            </div> --}}
        </div>
    </div>
    <!-- Edit Modal -->
<div wire:ignore.self class="modal fade" id="updateDataModal" data-bs-backdrop="static" tabindex="-1" role="dialog" aria-labelledby="updateModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
       <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="updateModalLabel">Actualizar Teléfono</h5>
                <button wire:click.prevent="cancel()" type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <form>
					<input type="hidden" wire:model="transportista_id_selected">
                    <div class="form-group">
                        <label for="num_celular"></label>
                        <input wire:model="num_celular" type="text" class="form-control" id="num_celular" placeholder="num_celular">
                        @error('num_celular') <span class="error text-danger">{{ $message }}</span> @enderror
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" wire:click.prevent="cancel()" class="btn btn-secondary" data-bs-dismiss="modal">Cerrar</button>
                <button type="button" wire:click.prevent="update()" class="btn btn-primary">Guardar</button>
            </div>
       </div>
    </div>
</div>
    <div class="card-body">
        {{-- <div class="table-responsive"> --}}
        <div class="row justify-content-end">

            <div class="col-auto pb-3">
                <button class="btn btn-success" wire:click="enviarPlacas()" type="submit">Enviar Placas</button>
            </div>
            <div class="col-auto pb-3">
                <a class="btn btn-info" href="{{route('excel.exports.sindicado.placa.habilitada',[$cia_id])}}">Imprimir</a>
            </div>
        </div>
            <table class="table table-sm table-bordered table-responsive-md table-striped">
                <thead>
                    <tr>
                        <th>#</th>
                        <th>Fecha</th>
                        <th>Placa</th>
                        <th>Cap.</th>
                        <th>Celular</th>
                        <th>Enviado</th>
                        <th>Con. Carga</th>
                        <th>Días Cola</th>
                        <th>Acción</th>
                    </tr>
                </thead>
                <tbody>
                    @php
                        $i=0;
                    @endphp
                    @foreach ($placasHabilitas as $item)
                        @php
                            $fecha = DateTime::createFromFormat('Y-m-d H:i:s.u',$item->fecha);
                            $diasDiff = $fechaNow->diff($fecha);
                            // dd($item);
                        @endphp
                        <tr>
                            <td>{{++$i}}</td>
                            <td>{{$fecha->format('d-m-Y H:i:s')}} </td>
                            <td>{{$item->placa}} </td>
                            <td>{{$item->capacidad_arrastre}} </td>
                            <td>{{$item->num_celular}} </td>
                            <td>{{$item->enviado?'SI':'NO'}}</td>
                            <td>
                                <div style="display: flex; justify-content:center; align-items:center">
                                    @livewire('cias.update-conocimiento-enviado', ['cia_habilitar_placa_id' => $item->id], key($item->id))
                                </div>
                            </td>
                            <td>{{$diasDiff->days}}</td>
                            <td>
                                <button class="btn btn-danger btn-sm"
                                        onclick="confirm('Confirma que desea eliminar la placa {{$item->placa}}?')||event.stopImmediatePropagation()"
                                        wire:click="eliminarPlaca({{ $item->id }})"
                                        >Eliminar
                                </button>
                                <button data-bs-toggle="modal" data-bs-target="#updateDataModal" class="btn btn-info btn-sm" wire:click="edit({{$item->transportista_id}})"><i class="fa fa-edit"></i> Editar </button>
                            </td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
        {{-- </div> --}}

    </div>
</div>

resources/views/livewire/cias/update-conocimiento-enviado.blade.php
<div>
    <input type="checkbox" wire:model="isChecked" wire:change="actualizarConocimientoEnviado">
</div>